spring.application.name=MyQuizApp

spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=${PORT:8080}


#spring.security.user.name=prakash 
#spring.security.user.password=1234

server.servlet.session.cookie.same-site=strict


